---
- name: Configure - Local Auth Set AAA - Cisco IOS
  cisco.ios.ios_config:
    lines:
      - "aaa new-model"
  when: ansible_net_system == "ios"

- name: Configure - Local Auth Set Login Method - Cisco IOS
  cisco.ios.ios_config:
    lines:
      - "aaa authentication login default {{ aaa_authentication1_login_default }}"
      - "aaa authorization exec default {{ aaa_authentication1_login_default }}"
  when: ansible_net_system == "ios"

- name: Configure - Local Auth Set Acct1 - Cisco IOS
  cisco.ios.ios_user:
    name: "{{ account1_name }}"
    privilege: "{{ account1_privilege }}"
    configured_password: "{{ account1_password }}"
    update_password: always
    state: present
  when: ansible_net_system == "ios"

- name: Configure - Local Auth Set Acct2 - Cisco IOS
  cisco.ios.ios_user:
    name: "{{ account2_name }}"
    privilege: "{{ account2_privilege }}"
    configured_password: "{{ account2_password }}"
    update_password: always
    state: present
  when: ansible_net_system == "ios"

- name: Configure - Enable Secret- Cisco IOS
  cisco.ios.ios_config:
    lines:
      - "enable secret {{ enable_password }}"
  when: ansible_net_system == "ios"

